// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.32.0
// source: kubewol/v1/agent.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// WatchSpec is the complete desired watch state sent on every reconcile.
// The agent treats missing entries as deletions.
type WatchSpec struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Watches       []*WatchEntry          `protobuf:"bytes,1,rep,name=watches,proto3" json:"watches,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WatchSpec) Reset() {
	*x = WatchSpec{}
	mi := &file_kubewol_v1_agent_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WatchSpec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WatchSpec) ProtoMessage() {}

func (x *WatchSpec) ProtoReflect() protoreflect.Message {
	mi := &file_kubewol_v1_agent_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WatchSpec.ProtoReflect.Descriptor instead.
func (*WatchSpec) Descriptor() ([]byte, []int) {
	return file_kubewol_v1_agent_proto_rawDescGZIP(), []int{0}
}

func (x *WatchSpec) GetWatches() []*WatchEntry {
	if x != nil {
		return x.Watches
	}
	return nil
}

// WatchEntry describes one Service that the agent must track. A Service
// with multiple TCP ports yields multiple entries; they share the workload
// target fields and differ only in port / node_port.
type WatchEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Namespace     string                 `protobuf:"bytes,1,opt,name=namespace,proto3" json:"namespace,omitempty"`
	Service       string                 `protobuf:"bytes,2,opt,name=service,proto3" json:"service,omitempty"`
	TargetKind    string                 `protobuf:"bytes,3,opt,name=target_kind,json=targetKind,proto3" json:"target_kind,omitempty"` // "Deployment" or "StatefulSet"
	TargetName    string                 `protobuf:"bytes,4,opt,name=target_name,json=targetName,proto3" json:"target_name,omitempty"`
	ClusterIp     string                 `protobuf:"bytes,5,opt,name=cluster_ip,json=clusterIp,proto3" json:"cluster_ip,omitempty"`         // IPv4 dotted quad
	Port          uint32                 `protobuf:"varint,6,opt,name=port,proto3" json:"port,omitempty"`                                   // host byte order
	NodePort      int32                  `protobuf:"varint,7,opt,name=node_port,json=nodePort,proto3" json:"node_port,omitempty"`           // 0 if the Service has no NodePort
	ProxyMode     bool                   `protobuf:"varint,8,opt,name=proxy_mode,json=proxyMode,proto3" json:"proxy_mode,omitempty"`        // BPF: SYN DROP on ingress
	RstSuppress   bool                   `protobuf:"varint,9,opt,name=rst_suppress,json=rstSuppress,proto3" json:"rst_suppress,omitempty"`  // BPF: RST/ICMP DROP on egress
	DirectScale   bool                   `protobuf:"varint,10,opt,name=direct_scale,json=directScale,proto3" json:"direct_scale,omitempty"` // agent emits SSE events for this entry
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WatchEntry) Reset() {
	*x = WatchEntry{}
	mi := &file_kubewol_v1_agent_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WatchEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WatchEntry) ProtoMessage() {}

func (x *WatchEntry) ProtoReflect() protoreflect.Message {
	mi := &file_kubewol_v1_agent_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WatchEntry.ProtoReflect.Descriptor instead.
func (*WatchEntry) Descriptor() ([]byte, []int) {
	return file_kubewol_v1_agent_proto_rawDescGZIP(), []int{1}
}

func (x *WatchEntry) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *WatchEntry) GetService() string {
	if x != nil {
		return x.Service
	}
	return ""
}

func (x *WatchEntry) GetTargetKind() string {
	if x != nil {
		return x.TargetKind
	}
	return ""
}

func (x *WatchEntry) GetTargetName() string {
	if x != nil {
		return x.TargetName
	}
	return ""
}

func (x *WatchEntry) GetClusterIp() string {
	if x != nil {
		return x.ClusterIp
	}
	return ""
}

func (x *WatchEntry) GetPort() uint32 {
	if x != nil {
		return x.Port
	}
	return 0
}

func (x *WatchEntry) GetNodePort() int32 {
	if x != nil {
		return x.NodePort
	}
	return 0
}

func (x *WatchEntry) GetProxyMode() bool {
	if x != nil {
		return x.ProxyMode
	}
	return false
}

func (x *WatchEntry) GetRstSuppress() bool {
	if x != nil {
		return x.RstSuppress
	}
	return false
}

func (x *WatchEntry) GetDirectScale() bool {
	if x != nil {
		return x.DirectScale
	}
	return false
}

type PutWatchesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PutWatchesResponse) Reset() {
	*x = PutWatchesResponse{}
	mi := &file_kubewol_v1_agent_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PutWatchesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PutWatchesResponse) ProtoMessage() {}

func (x *PutWatchesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_kubewol_v1_agent_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PutWatchesResponse.ProtoReflect.Descriptor instead.
func (*PutWatchesResponse) Descriptor() ([]byte, []int) {
	return file_kubewol_v1_agent_proto_rawDescGZIP(), []int{2}
}

type SubscribeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubscribeRequest) Reset() {
	*x = SubscribeRequest{}
	mi := &file_kubewol_v1_agent_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubscribeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscribeRequest) ProtoMessage() {}

func (x *SubscribeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_kubewol_v1_agent_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscribeRequest.ProtoReflect.Descriptor instead.
func (*SubscribeRequest) Descriptor() ([]byte, []int) {
	return file_kubewol_v1_agent_proto_rawDescGZIP(), []int{3}
}

// SynEvent is emitted per direct-scale-eligible SYN observed by the agent.
type SynEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Namespace     string                 `protobuf:"bytes,1,opt,name=namespace,proto3" json:"namespace,omitempty"`
	TargetKind    string                 `protobuf:"bytes,2,opt,name=target_kind,json=targetKind,proto3" json:"target_kind,omitempty"`
	TargetName    string                 `protobuf:"bytes,3,opt,name=target_name,json=targetName,proto3" json:"target_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SynEvent) Reset() {
	*x = SynEvent{}
	mi := &file_kubewol_v1_agent_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SynEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SynEvent) ProtoMessage() {}

func (x *SynEvent) ProtoReflect() protoreflect.Message {
	mi := &file_kubewol_v1_agent_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SynEvent.ProtoReflect.Descriptor instead.
func (*SynEvent) Descriptor() ([]byte, []int) {
	return file_kubewol_v1_agent_proto_rawDescGZIP(), []int{4}
}

func (x *SynEvent) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *SynEvent) GetTargetKind() string {
	if x != nil {
		return x.TargetKind
	}
	return ""
}

func (x *SynEvent) GetTargetName() string {
	if x != nil {
		return x.TargetName
	}
	return ""
}

var File_kubewol_v1_agent_proto protoreflect.FileDescriptor

const file_kubewol_v1_agent_proto_rawDesc = "" +
	"\n" +
	"\x16kubewol/v1/agent.proto\x12\n" +
	"kubewol.v1\"=\n" +
	"\tWatchSpec\x120\n" +
	"\awatches\x18\x01 \x03(\v2\x16.kubewol.v1.WatchEntryR\awatches\"\xbb\x02\n" +
	"\n" +
	"WatchEntry\x12\x1c\n" +
	"\tnamespace\x18\x01 \x01(\tR\tnamespace\x12\x18\n" +
	"\aservice\x18\x02 \x01(\tR\aservice\x12\x1f\n" +
	"\vtarget_kind\x18\x03 \x01(\tR\n" +
	"targetKind\x12\x1f\n" +
	"\vtarget_name\x18\x04 \x01(\tR\n" +
	"targetName\x12\x1d\n" +
	"\n" +
	"cluster_ip\x18\x05 \x01(\tR\tclusterIp\x12\x12\n" +
	"\x04port\x18\x06 \x01(\rR\x04port\x12\x1b\n" +
	"\tnode_port\x18\a \x01(\x05R\bnodePort\x12\x1d\n" +
	"\n" +
	"proxy_mode\x18\b \x01(\bR\tproxyMode\x12!\n" +
	"\frst_suppress\x18\t \x01(\bR\vrstSuppress\x12!\n" +
	"\fdirect_scale\x18\n" +
	" \x01(\bR\vdirectScale\"\x14\n" +
	"\x12PutWatchesResponse\"\x12\n" +
	"\x10SubscribeRequest\"j\n" +
	"\bSynEvent\x12\x1c\n" +
	"\tnamespace\x18\x01 \x01(\tR\tnamespace\x12\x1f\n" +
	"\vtarget_kind\x18\x02 \x01(\tR\n" +
	"targetKind\x12\x1f\n" +
	"\vtarget_name\x18\x03 \x01(\tR\n" +
	"targetName2\x98\x01\n" +
	"\x05Agent\x12C\n" +
	"\n" +
	"PutWatches\x12\x15.kubewol.v1.WatchSpec\x1a\x1e.kubewol.v1.PutWatchesResponse\x12J\n" +
	"\x12SubscribeSynEvents\x12\x1c.kubewol.v1.SubscribeRequest\x1a\x14.kubewol.v1.SynEvent0\x01B5Z3github.com/munenick/kubewol/internal/agentapi/pb;pbb\x06proto3"

var (
	file_kubewol_v1_agent_proto_rawDescOnce sync.Once
	file_kubewol_v1_agent_proto_rawDescData []byte
)

func file_kubewol_v1_agent_proto_rawDescGZIP() []byte {
	file_kubewol_v1_agent_proto_rawDescOnce.Do(func() {
		file_kubewol_v1_agent_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_kubewol_v1_agent_proto_rawDesc), len(file_kubewol_v1_agent_proto_rawDesc)))
	})
	return file_kubewol_v1_agent_proto_rawDescData
}

var file_kubewol_v1_agent_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_kubewol_v1_agent_proto_goTypes = []any{
	(*WatchSpec)(nil),          // 0: kubewol.v1.WatchSpec
	(*WatchEntry)(nil),         // 1: kubewol.v1.WatchEntry
	(*PutWatchesResponse)(nil), // 2: kubewol.v1.PutWatchesResponse
	(*SubscribeRequest)(nil),   // 3: kubewol.v1.SubscribeRequest
	(*SynEvent)(nil),           // 4: kubewol.v1.SynEvent
}
var file_kubewol_v1_agent_proto_depIdxs = []int32{
	1, // 0: kubewol.v1.WatchSpec.watches:type_name -> kubewol.v1.WatchEntry
	0, // 1: kubewol.v1.Agent.PutWatches:input_type -> kubewol.v1.WatchSpec
	3, // 2: kubewol.v1.Agent.SubscribeSynEvents:input_type -> kubewol.v1.SubscribeRequest
	2, // 3: kubewol.v1.Agent.PutWatches:output_type -> kubewol.v1.PutWatchesResponse
	4, // 4: kubewol.v1.Agent.SubscribeSynEvents:output_type -> kubewol.v1.SynEvent
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_kubewol_v1_agent_proto_init() }
func file_kubewol_v1_agent_proto_init() {
	if File_kubewol_v1_agent_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_kubewol_v1_agent_proto_rawDesc), len(file_kubewol_v1_agent_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_kubewol_v1_agent_proto_goTypes,
		DependencyIndexes: file_kubewol_v1_agent_proto_depIdxs,
		MessageInfos:      file_kubewol_v1_agent_proto_msgTypes,
	}.Build()
	File_kubewol_v1_agent_proto = out.File
	file_kubewol_v1_agent_proto_goTypes = nil
	file_kubewol_v1_agent_proto_depIdxs = nil
}
