// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v6.32.0
// source: kubewol/v1/agent.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Agent_PutWatches_FullMethodName         = "/kubewol.v1.Agent/PutWatches"
	Agent_SubscribeSynEvents_FullMethodName = "/kubewol.v1.Agent/SubscribeSynEvents"
)

// AgentClient is the client API for Agent service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Agent is the gRPC surface served by the kubewol agent DaemonSet. The
// controller Deployment is the only expected caller; authentication is
// enforced by a unary/stream interceptor that validates the bearer token in
// the "authorization" metadata against kube-apiserver via TokenReview with
// spec.audiences=["kubewol.io/agent-api"]. Any token whose aud claim does
// not match that audience is rejected before reaching a handler.
type AgentClient interface {
	// PutWatches replaces the agent's full desired watch state. The
	// controller sends the complete set on every reconcile; the agent diffs
	// against its in-memory snapshot and updates BPF maps accordingly.
	PutWatches(ctx context.Context, in *WatchSpec, opts ...grpc.CallOption) (*PutWatchesResponse, error)
	// SubscribeSynEvents opens a server-side stream that emits one message
	// per direct-scale-eligible SYN observed by the BPF ring buffer. The
	// controller maintains one stream per agent pod and triggers the
	// direct-scale fast path when a message arrives.
	SubscribeSynEvents(ctx context.Context, in *SubscribeRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[SynEvent], error)
}

type agentClient struct {
	cc grpc.ClientConnInterface
}

func NewAgentClient(cc grpc.ClientConnInterface) AgentClient {
	return &agentClient{cc}
}

func (c *agentClient) PutWatches(ctx context.Context, in *WatchSpec, opts ...grpc.CallOption) (*PutWatchesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PutWatchesResponse)
	err := c.cc.Invoke(ctx, Agent_PutWatches_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentClient) SubscribeSynEvents(ctx context.Context, in *SubscribeRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[SynEvent], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Agent_ServiceDesc.Streams[0], Agent_SubscribeSynEvents_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[SubscribeRequest, SynEvent]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Agent_SubscribeSynEventsClient = grpc.ServerStreamingClient[SynEvent]

// AgentServer is the server API for Agent service.
// All implementations must embed UnimplementedAgentServer
// for forward compatibility.
//
// Agent is the gRPC surface served by the kubewol agent DaemonSet. The
// controller Deployment is the only expected caller; authentication is
// enforced by a unary/stream interceptor that validates the bearer token in
// the "authorization" metadata against kube-apiserver via TokenReview with
// spec.audiences=["kubewol.io/agent-api"]. Any token whose aud claim does
// not match that audience is rejected before reaching a handler.
type AgentServer interface {
	// PutWatches replaces the agent's full desired watch state. The
	// controller sends the complete set on every reconcile; the agent diffs
	// against its in-memory snapshot and updates BPF maps accordingly.
	PutWatches(context.Context, *WatchSpec) (*PutWatchesResponse, error)
	// SubscribeSynEvents opens a server-side stream that emits one message
	// per direct-scale-eligible SYN observed by the BPF ring buffer. The
	// controller maintains one stream per agent pod and triggers the
	// direct-scale fast path when a message arrives.
	SubscribeSynEvents(*SubscribeRequest, grpc.ServerStreamingServer[SynEvent]) error
	mustEmbedUnimplementedAgentServer()
}

// UnimplementedAgentServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAgentServer struct{}

func (UnimplementedAgentServer) PutWatches(context.Context, *WatchSpec) (*PutWatchesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method PutWatches not implemented")
}
func (UnimplementedAgentServer) SubscribeSynEvents(*SubscribeRequest, grpc.ServerStreamingServer[SynEvent]) error {
	return status.Error(codes.Unimplemented, "method SubscribeSynEvents not implemented")
}
func (UnimplementedAgentServer) mustEmbedUnimplementedAgentServer() {}
func (UnimplementedAgentServer) testEmbeddedByValue()               {}

// UnsafeAgentServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AgentServer will
// result in compilation errors.
type UnsafeAgentServer interface {
	mustEmbedUnimplementedAgentServer()
}

func RegisterAgentServer(s grpc.ServiceRegistrar, srv AgentServer) {
	// If the following call panics, it indicates UnimplementedAgentServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Agent_ServiceDesc, srv)
}

func _Agent_PutWatches_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WatchSpec)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServer).PutWatches(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Agent_PutWatches_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServer).PutWatches(ctx, req.(*WatchSpec))
	}
	return interceptor(ctx, in, info, handler)
}

func _Agent_SubscribeSynEvents_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(SubscribeRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(AgentServer).SubscribeSynEvents(m, &grpc.GenericServerStream[SubscribeRequest, SynEvent]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Agent_SubscribeSynEventsServer = grpc.ServerStreamingServer[SynEvent]

// Agent_ServiceDesc is the grpc.ServiceDesc for Agent service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Agent_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "kubewol.v1.Agent",
	HandlerType: (*AgentServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "PutWatches",
			Handler:    _Agent_PutWatches_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "SubscribeSynEvents",
			Handler:       _Agent_SubscribeSynEvents_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "kubewol/v1/agent.proto",
}
